POST http://wb:10088/book/add_index
Content-Type: application/json

{

  "name": "十万个为什么-2",
  "author": "佚名",
  "contents": [
    {
      "page": 2,
      "title": "序言"
    },
    {
      "page": 10,
      "title": "为什么秦朝灭亡的那么早？"
    }
  ],
  "tags": ["为什么","中文","问题","历史"]
}


###
#
GET http://localhost:10088/book/


###

GET http://localhost:10088/book/八个


###

PUT http://localhost:10088/book/1

<> 2019-09-12T093656.400.json

###

DELETE http://localhost:10088/book/1

<> 2019-09-12T094116.200.txt
<> 2019-09-12T093925.200.txt

###

GET http://localhost:10088/book/序

<> 2019-09-12T113801.500.json

###

GET http://localhost:10088/book/findContentsTitle?title=序

<> 2019-09-12T114004.200.json

###

GET http://localhost:10088/book/findBytags?tag=史

###
#getAll
GET http://localhost:10088/book/getAll?page=0&size=6&sort=name


###

GET http://localhost:10088/book/count

<> 2019-09-12T023307.200.json

###

DELETE http://localhost:10088/book/delete

###
PUT localhost:9200/book_index4?pretty
Content-Type: application/json

{
  "mappings": {
    "book": {
      "properties": {
        "name": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword"
            }
          }
        }
      }
    }
  }
}

<> 2019-09-12T053107.200.json
<> 2019-09-12T053035.400.json
<> 2019-09-12T053030.400.json
<> 2019-09-12T053013.400.json
<> 2019-09-12T050213.400.json
<> 2019-09-12T045336.200.json

### 可以用transport 设置mapping参数 这个尝试放到listener里来做
PUT localhost:9200/book_index3/_mapping/book3?pretty
Content-Type: application/json


{
  "properties": {
    "name": {
      "type":     "text",
      "fielddata": true
    }
  }
}

<> 2019-09-12T063156.200.json
<> 2019-09-12T063148.404.json
<> 2019-09-12T063137.404.json
<> 2019-09-12T063130.200.json
<> 2019-09-12T045805.200.json
<> 2019-09-12T045731.400.json
<> 2019-09-12T045701.400.txt
<> 2019-09-12T045647.400.json

###


